#!/usr/bin/env python3
import os.path
import sys
import subprocess
import time
import argparse
from argparse import ArgumentTypeError as ArgError
import syslog
from socket import gethostname
import pfscripts as pfs


def validate_args(parser):
    args = parser.parse_args()
    args.source_path = args.paths[:-1]
    args.dest_path = args.paths[-1]
    error = None
    try:
        base_name = os.path.dirname(args.source_path[0])
        if args.recursive:
            for i in args.source_path:
                if os.path.dirname(i) != base_name:
                    error = "All sources for a recursive copy must be" + \
                        " contained within the same directory."
                    raise ArgError
        if args.dest_path.split()[-1] == "/":
            base_dest_name = os.path.dirname(args.dest_path)
        else:
            base_dest_name = args.dest_path
        if base_dest_name and not os.path.exists(base_dest_name):
            error = f"{args.dest_path} - No such file or directory"
            raise ArgError
        return args
    except ArgError:
        print("ERROR:")
        print(error)
        parser.print_help()
        sys.exit(1)


def main(parser):
    args = validate_args(parser)
    if not args:
        parser.print_help()
        sys.exit(1)
    config = pfs.Config(parser.prog)
    jid = pfs.get_jid()
    commands = pfs.Commands()
    commands.add("-w", pfs.Work.COMPARE)
    commands.add("-j", jid)

    if config.logging:
        commands.add("-l")
    if args.data:
        commands.add("-D")
    if args.verbose:
        commands.add("-v")
    if args.preserve:
        commands.add("-o")
    if args.exclude is not None:
        commands.add("-e")
        commands.add(args.exclude)
    if args.recursive:
        commands.add("-r")

    commands.add("-s", config.write_size)

    commands.add("-C", config.chunk_at)
    commands.add("-S", config.chunk_size)
    if config.direct_io_write:
        commands.add("-W")
    if config.direct_io_read:
        commands.add("-R")
    src_fixed = pfs.get_fixed_source(args.source_path,args.symlinks)
    dest_fixed = pfs.get_fixed_dest(args.dest_path,args.symlinks)
    commands.add("-c", *dest_fixed)
    commands.add("-p", *src_fixed)

    pfcmd = pfs.Commands()

    pfcmd.add(config.mpirun)
    # should return the MPI installation root
    mpiroot = os.path.dirname(os.path.dirname(pfs.findexec(config.mpirun)))
    # this is a fix for "orted: command not found" issue
    pfcmd.add("-prefix", mpiroot)

    # this is a fix for "no preset parameters found" issue w/ mlnx IB devices
    pfcmd.add("--mca", "btl", "^openib")

    # silence ssh /etc/issue output
    pfcmd.add("--mca", "plm_rsh_args", "\"-o LogLevel=ERROR\"" )

    # silence mpirun informational messages
    pfcmd.add("-q")

    # Add in the dangerous flags that are necessary for running in production
    pfcmd.add("--oversubscribe")
    pfcmd.add("--allow-run-as-root")
    pfcmd.add("--map-by", "node")

    if "all" not in config.node_list:
        pfcmd.add("-host", ",".join(config.node_list))
    pfcmd.add("-n", str(config.total_procs))
    pfcmd.add(pfs.PF.PFTOOL)

    pfcmd.add(*commands.commands)
    host = gethostname()
    print("Launched %s from host %s at: %s" % (
        sys.argv[0], host, time.strftime(
            "%a %b %d %H:%M:%S %Z %Y", time.localtime())))

    if config.logging:
        pfs.write_log("[pfcm] [%s] Begin Date: %s" % (
            jid, time.strftime("%a %b %d %H:%M:%S %Z %Y", time.localtime())))
        pfs.write_log("[pfcm] [%s] CMD %s" % (jid, pfcmd))

    status = subprocess.call(pfcmd.commands)
    if(status != 0):
        print("ERROR: %s failed" % sys.argv[0])
        if config.logging:
            pfs.write_log("[pfcm] [%s] PFCM failed." % (jid), syslog.LOG_ERR)

    print("Job finished at: %s" %
          (time.strftime("%a %b %d %H:%M:%S %Z %Y", time.localtime())))
    if config.logging:
        pfs.write_log("[pfcm] [%s] Job End at: %s" % (
            jid, time.strftime("%a %b %d %H:%M:%S %Z %Y", time.localtime())))

    sys.exit(status)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        'pfcm',
        usage="pfcm [options] sourcePath destinationPath",
        description="compare file(s) from sourcePath to destinationPath in parallel"
    )

    parser.add_argument(
        'paths',
        nargs='*',
        help=argparse.SUPPRESS
    )

    parser.add_argument(
        '-R',
        '--recursive',
        action='store_true',
        help='Recursive action',
        default=False
    )

    parser.add_argument(
        '-D',
        '--data',
        action='store_true',
        help='Compare data content of files, in addition to metadata',
        default=False
    )

    parser.add_argument(
        '-p',
        '--preserve',
        action='store_true',
        help='Consider user/group ownership when comparing files to copy',
        default=False
    )

    parser.add_argument(
        '-v',
        '--verbose',
        action='store_true',
        help='Verbose output',
        default=False
    )

    parser.add_argument(
        '-e',
        '--exclude',
        type=str,
        help='Exclude pattern',
        default=None
    )

    parser.add_argument(
        '-s',
        '--symlinks',
        action='store_true',
        help='Do not dereference symlink arguments ( source or dest )',
        default=False
    )

    if len(sys.argv) < 2:
        parser.print_usage()
        sys.exit(1)

    main(parser)
