#!/usr/bin/env python
import os.path, sys, pwd, grp, subprocess
from optparse import OptionParser
from pfscripts import *

def main():
  parser = OptionParser()
  parser.usage = "%prog [options] sourcePath"
  parser.description = "%prog --  list file(s) based on sourcePath in parallel"
  parser.add_option("-R", dest="recurse", default=False, action="store_true", help="list directories recursively")
  parser.add_option("-v", dest="verbose", default=False, action="store_true", help="verbose result output")
  parser.add_option("-i", dest="input_list", help="input file list")
  (options, args) = parser.parse_args()

  config = parse_config()


  jid = get_jid()
  src = args
  commands = Commands()
  commands.add("-w", Work.LS)
  commands.add("-j", jid)

  logging = False
  try:
    l = config.get("environment", "logging")
  except:
    parser.error("please specify whether logging should be enabled (e.g. logging: True)")

  if l.lower() == "true":
    logging = True
    commands.add("-l")

  if options.verbose:
    commands.add("-v");

  if options.input_list:
    commands.add ("-i", options.input_list)
  elif src:
    base_name = os.path.dirname(src[0])
    if options.recurse:
      commands.add("-r")

    commands.add("-p", *src)
  else:
    parser.error("please include a source path or input list")

  threaded = False
  try:
    t = config.get("environment", "threaded")
  except:
    parser.error("please specify whether the program is threaded or not in the environment section of the config file (e.g. threaded: True)")

  if t.lower() == "true":
    threaded = True

  pfcmd = Commands()
  num_procs = config.get("num_procs", "pfls")


  if threaded:
    pfcmd.add(pftool)
    pfcmd.add("-nthread", num_procs)
  else:
    try:
      mpigo = config.get("environment", "mpirun")
    except:
      parser.error("please specify the mpirun path in the environment section of the config file (e.g. mpirun: /path/to/mpirun)")

    try:
      host_list = map(lambda x: x[0].lower(), filter(lambda x: x[1] == "ON", config.items("active_nodes")))
    except:
      parser.error("please specify at least 1 host in active_nodes section of the config file (e.g. localhost: ON)")
      
    pfcmd.add(mpigo)
    mpiroot= os.path.dirname(os.path.dirname(findexec(mpigo)))		# should return the MPI installation root
    pfcmd.add("-prefix", mpiroot)					# this is a fix for "orted: command not found" issue

    # Add darshan logging support if its available (this must be called after adding mpigo)
    add_darshan(config, pfcmd)

    if "all" not in host_list:
        pfcmd.add("-host", ",".join(host_list))
    pfcmd.add("-n", num_procs)
    pfcmd.add(pftool)
    

  pfcmd.add(*commands.commands)

  host = gethostname()

  print "Launched %s from host %s at: %s"%(sys.argv[0], host, time.strftime("%a %b %d %H:%M:%S %Z %Y", time.localtime()))
  
  if logging:
    write_log("[pfls] [%s] Begin Date: %s"%(jid, time.strftime("%a %b %d %H:%M:%S %Z %Y", time.localtime())))
    write_log("[pfls] [%s] CMD %s"%(jid, pfcmd))


  status = subprocess.call(pfcmd.commands)
  if(status != 0):
    print "ERROR: %s failed"%sys.argv[0]
    if logging:
      write_log("[pfls] [%s] PFLS failed."%(jid), LOG_ERR)

  
  print "Job finished at: %s"%(time.strftime("%a %b %d %H:%M:%S %Z %Y", time.localtime()))
  if logging:
    write_log("[pfls] [%s] Job End at: %s"%(jid, time.strftime("%a %b %d %H:%M:%S %Z %Y", time.localtime())))


if __name__ == "__main__":
  main()
